apiVersion: v1
kind: Service
metadata: 
  name: {{ .Release.Name }}-{{ .Values.appname }}-service
  namespace: {{ .Release.Name }}-{{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ default 8080 (index .Values.containers.ports 0).port }}
      targetPort: {{ default 8080 (index .Values.containers.ports 0).targetPort }}
  selector:
    role: {{ .Values.labels.role }}
    env: {{ .Values.labels.env }}
