apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Values.cartservice.name }}-deployment"
  namespace: "{{ .Release.Name }}-{{ .Values.namespace }}-{{ .Values.environment }}"
spec:
  replicas: {{ .Values.cartservice.pod.replicas }}
  selector:
    matchLabels:
      {{- include "common_labels" . | nindent 6 }}
      {{- include "cartservice_labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common_labels" . | nindent 8 }}
        {{- include "cartservice_labels" . | nindent 8 }}
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: "{{ .Values.cartservice.name }}-container"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        {{- with .Values.cartservice.container}}
        image: "{{ .image.name }}:{{ .image.tag }}"
        ports:
        - containerPort: {{ .port }}
        env:
        - name: REDIS_ADDR
          value: "{{ $.Release.Name }}-{{ $.Values.redis_cart.name }}-service:{{ $.Values.redis_cart.service.port }}"
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
        readinessProbe:
          initialDelaySeconds: 15
          grpc:
            port: {{ .port }}
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          grpc:
            port: {{ .port }}
        {{- end}}