apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Values.emailservice.name }}-deployment"
  namespace: "{{ .Release.Name }}-{{ .Values.namespace }}-{{ .Values.environment }}"
spec:
  replicas: {{ .Values.emailservice.pod.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
      service: {{ .Values.emailservice.name }}
      environment: {{ .Values.environment }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
        service: {{ .Values.emailservice.name }}
        environment: {{ .Values.environment }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: "{{ .Release.Name }}-{{ .Values.emailservice.name }}-container"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: "{{ .Values.emailservice.container.image.name }}:{{ .Values.emailservice.container.image.tag }}"
        ports:
        - containerPort: {{ .Values.emailservice.container.port }}
        env:
        - name: PORT
          value: "{{ .Values.emailservice.container.port }}"
        - name: DISABLE_PROFILER
          value: "{{ .Values.emailservice.container.disable_profiler }}"
        readinessProbe:
          periodSeconds: 5
          grpc:
            port: {{ .Values.emailservice.container.port }}
        livenessProbe:
          periodSeconds: 5
          grpc:
            port: {{ .Values.emailservice.container.port }}
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi