apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Values.loadgenerator.name }}-deployment"
  labels:
    {{- include "common_labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.loadgenerator.pod.replicas }}
  selector:
    matchLabels:
      {{- include "common_labels" . | nindent 6 }}
      {{- include "loadgenerator_labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common_labels" . | nindent 8 }}
        {{- include "loadgenerator_labels" . | nindent 8 }}
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      initContainers:
      - command:
        - /bin/sh
        - -exc
        - |
          echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
          if test $STATUSCODE -ne 200; then
              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
              exit 1
          fi
        name: "{{ .Release.Name }}-{{ .Values.loadgenerator.name }}-frontend-check"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        {{- with .Values.loadgenerator.container}}
        image: "{{ .image.name }}:{{ .image.tag }}"
        env:
        - name: FRONTEND_ADDR
          value: "{{ $.Release.Name }}-{{ $.Values.frontend.name }}-service:{{ $.Values.frontend.service.port }}"
      containers:
      - name: main
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: "{{ .image.name }}:{{ .image.tag }}"
        {{- end}}
        env:
        - name: FRONTEND_ADDR
          value: "{{ .Release.Name }}-{{ .Values.frontend.name }}-service:{{ .Values.frontend.service.port }}"
        - name: USERS
          value: "{{ .Values.loadgenerator.users }}"
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
