apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Values.recommendationservice.name }}-deployment"
  namespace: "{{ .Release.Name }}-{{ .Values.namespace }}-{{ .Values.environment }}"
spec:
  replicas: {{ .Values.recommendationservice.pod.replicas }}
  selector:
    matchLabels:
      {{- include "common_labels" . | nindent 6 }}
      {{- include "recommendationservice_labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common_labels" . | nindent 8 }}
        {{- include "recommendationservice_labels" . | nindent 8 }}
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: "{{ .Release.Name }}-{{ .Values.recommendationservice.name }}-container"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: "{{ .Values.recommendationservice.container.image.name }}:{{ .Values.recommendationservice.container.image.tag }}"
        ports:
        - containerPort: {{ .Values.recommendationservice.container.port }}
        readinessProbe:
          periodSeconds: 5
          grpc:
            port: {{ .Values.recommendationservice.container.port }}
        livenessProbe:
          periodSeconds: 5
          grpc:
            port: {{ .Values.recommendationservice.container.port }}
        env:
        - name: PORT
          value: "{{ .Values.recommendationservice.container.port }}"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "{{ .Release.Name }}-{{ .Values.productcatalogservice.name }}-service:{{ .Values.productcatalogservice.service.port }}"
        - name: DISABLE_PROFILER
          value: "{{ .Values.recommendationservice.container.disable_profiler }}"
        resources:
          requests:
            cpu: 100m
            memory: 220Mi
          limits:
            cpu: 200m
            memory: 450Mi